<?xml version='1.0'?>
<robot name="mogi_bot2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  <material name="silver">
    <color rgba="0.8 0.8 0.8 1"/>
  </material>

  <xacro:property name="base_mass" value="15.0" />
  <xacro:property name="wheel_mass" value="5.0" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_separation" value="0.3" />
  <xacro:property name="caster_radius" value="0.05" />

  <xacro:property name="gimbal_base_mass" value="0.5" />
  <xacro:property name="gimbal_yaw_mass" value="0.5" />
  <xacro:property name="barrel_mass" value="0.3" />
  <xacro:property name="camera_mass" value="0.3" />
  <xacro:property name="barrel_length" value="0.2" />
  <xacro:property name="barrel_radius" value="0.02" />

  <link name="base_footprint2">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="base_footprint_joint2" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint2"/>
    <child link="base_link2" />
  </joint>

  <link name='base_link2'>
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0625" ixy="0" ixz="0"
          iyy="0.2125" iyz="0"
          izz="0.25"
      />
    </inertial>

    <collision name='collision2'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".4 .2 .1"/>
      </geometry>
    </collision>

    <visual name='base_link_visual2'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".4 .2 .1"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <link name="caster_wheel_link2">
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <collision name="caster_wheel_collision2">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>

    <visual name="caster_wheel_visual2">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="caster_swivel_joint2" type="continuous">
    <origin xyz="0.25 0 -0.05" rpy="0 0 0"/>
    <parent link="base_link2"/>
    <child link="caster_swivel_link2"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="caster_swivel_link2">
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="caster_wheel_joint2" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="caster_swivel_link2"/>
    <child link="caster_wheel_link2"/>
  </joint>

  <link name="caster_wheel_link_22">
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <collision name="caster_wheel_collision_22">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>

    <visual name="caster_wheel_visual_22">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="caster_swivel_joint_22" type="continuous">
    <origin xyz="-0.25 0 -0.05" rpy="0 0 0"/>
    <parent link="base_link2"/>
    <child link="caster_swivel_link_22"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="caster_swivel_link_22">
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="caster_wheel_joint_22" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="caster_swivel_link_22"/>
    <child link="caster_wheel_link_22"/>
  </joint>

  <joint name="gimbal_base_joint2" type="fixed">
    <origin xyz="0.1 0 0.05" rpy="0 0 0" />
    <parent link="base_link2"/>
    <child link="gimbal_base2" />
  </joint>

  <link name='gimbal_base2'>
    <inertial>
      <mass value="${gimbal_base_mass}"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <inertia
          ixx="0.001" ixy="0" ixz="0"
          iyy="0.001" iyz="0"
          izz="0.001"
      />
    </inertial>

    <collision name='gimbal_base_collision2'>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
    </collision>

    <visual name='gimbal_base_visual2'>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
      <material name="silver"/>
    </visual>
  </link>

  <joint name="gimbal_yaw_joint2" type="revolute">
    <origin xyz="0 0 0.04" rpy="0 0 0" />
    <parent link="gimbal_base2"/>
    <child link="gimbal_yaw2" />
    <axis xyz="0 0 1" />
    <limit lower="-3.14" upper="3.14" effort="10" velocity="2.0"/>
  </joint>

  <link name='gimbal_yaw2'>
    <inertial>
      <mass value="${gimbal_yaw_mass}"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <inertia
          ixx="0.0005" ixy="0" ixz="0"
          iyy="0.0005" iyz="0"
          izz="0.0005"
      />
    </inertial>

    <collision name='gimbal_yaw_collision2'>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.08 0.04"/>
      </geometry>
    </collision>

    <visual name='gimbal_yaw_visual2'>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.08 0.04"/>
      </geometry>
      <material name="gray"/>
    </visual>
  </link>

  <joint name="barrel_joint2" type="fixed">
    <origin xyz="0 0 0.04" rpy="0 0 0" />
    <parent link="gimbal_yaw2"/>
    <child link="barrel_link2" />
  </joint>

  <link name='barrel_link2'>
    <inertial>
      <mass value="${barrel_mass}"/>
      <origin xyz="${barrel_length/2} 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0003" ixy="0" ixz="0"
          iyy="0.0003" iyz="0"
          izz="0.0003"
      />
    </inertial>

    <collision name='barrel_collision2'>
      <origin xyz="${barrel_length/2} 0 0" rpy="1.57 0 1.57"/>
      <geometry>
        <cylinder radius="${barrel_radius}" length="${barrel_length}"/>
      </geometry>
    </collision>

    <visual name='barrel_visual2'>
      <origin xyz="${barrel_length/2} 0 0" rpy="1.57 0 1.57"/>
      <geometry>
        <cylinder radius="${barrel_radius}" length="${barrel_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="camera_joint2" type="fixed">
    <origin xyz="${barrel_length} 0 0" rpy="0 0 0" />
    <parent link="barrel_link2"/>
    <child link="camera_link2" />
  </joint>

  <link name='camera_link2'>
    <inertial>
      <mass value="${camera_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0" ixz="0"
          iyy="0.0001" iyz="0"
          izz="0.0001"
      />
    </inertial>

    <visual name='camera_visual2'>
      <origin xyz="0 0 0" rpy="0 1.5708 1.5708"/>
      <geometry>
        <cylinder radius="0.015" length="0.04"/>
      </geometry>
      <material name="black"/>
    </visual>

    <visual name='camera_lens_visual2'>
      <origin xyz="0.02 0 0" rpy="0 1.5708 1.5708"/>
      <geometry>
        <cylinder radius="0.008" length="0.005"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision name='camera_collision2'>
      <origin xyz="0 0 0" rpy="0 1.5708 1.5708"/>
      <geometry>
        <cylinder radius="0.015" length="0.04"/>
      </geometry>
    </collision>

    <sensor name="camera_sensor2" type="camera">
      <pose>0.02 0 0 0 -1.5708 1.5708</pose>
      <camera name="camera2">
        <horizontal_fov>1.0472</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <always_on>1</always_on>
      <update_rate>30</update_rate>
    </sensor>
  </link>

  <joint type="continuous" name="left_wheel_joint2">
    <origin xyz="0 0.125 0" rpy="0 0 0"/>
    <child link="left_wheel2"/>
    <parent link="base_link2"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name='left_wheel2'>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.014" ixy="0" ixz="0"
          iyy="0.014" iyz="0"
          izz="0.025"
      />
    </inertial>

    <collision name="left_wheel_collision2">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>

    <visual name='left_wheel_visual2'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint type="continuous" name="right_wheel_joint2">
    <origin xyz="0 -0.125 0" rpy="0 0 0"/>
    <child link="right_wheel2"/>
    <parent link="base_link2"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name='right_wheel2'>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.014" ixy="0" ixz="0"
          iyy="0.014" iyz="0"
          izz="0.025"
      />
    </inertial>

    <collision name="right_wheel_collision2">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>

    <visual name='right_wheel_visual2'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <gazebo>
    <plugin name="gazebo_ros2_control2" filename="libgazebo_ros2_control.so">
      <parameters>$(find two_wheeled_cart)/config/controller.yaml</parameters>
    </plugin>
  </gazebo>

  <gazebo reference="camera_link2">
    <sensor type="camera" name="camera12">
      <update_rate>30.0</update_rate>
      <camera name="head2">
        <horizontal_fov>1.0472</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>100</far>
        </clip>
      </camera>
      <plugin name="camera_controller2" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/mogi_bot2</namespace>
          <remapping>image_raw:=camera/image_raw</remapping>
          <remapping>camera_info:=camera/camera_info</remapping>
        </ros>
        <camera_name>camera2</camera_name>
        <frame_name>camera_link2</frame_name>
        <hack_baseline>0.07</hack_baseline>
      </plugin>
    </sensor>
  </gazebo>

  <ros2_control name="mogi_hardware_interface2" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <joint name="left_wheel_joint2">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_wheel_joint2">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="gimbal_yaw_joint2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>