<?xml version='1.0'?>
<robot name="red_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <material name="red">
    <color rgba="0.8 0 0 1"/>
  </material>
  <material name="yellow">
    <color rgba="1 1 0 1"/>
  </material>

  <xacro:property name="base_mass" value="15.0" />
  <xacro:property name="wheel_mass" value="5.0" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_separation" value="0.3" />
  <xacro:property name="wheelbase" value="0.4" />

  <link name="odom">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="odom_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="odom"/>
    <child link="base_footprint"/>
  </joint>

  <link name="base_footprint">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <link name='base_link'>
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0625" ixy="0" ixz="0" iyy="0.2125" iyz="0" izz="0.25"/>
    </inertial>
    <collision name='collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size=".4 .2 .1"/></geometry>
    </collision>
    <visual name='base_link_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size=".4 .2 .1"/></geometry>
      <material name="red"/>
    </visual>
  </link>

  <xacro:macro name="wheel" params="prefix xyz">
    <joint type="continuous" name="${prefix}_wheel_joint">
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <child link="${prefix}_wheel"/>
      <parent link="base_link"/>
      <axis xyz="0 1 0"/>
      <limit effort="100" velocity="10"/>
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <link name='${prefix}_wheel'>
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <inertia ixx="0.014" ixy="0" ixz="0" iyy="0.014" iyz="0" izz="0.025"/>
      </inertial>
      <collision name="${prefix}_wheel_collision">
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
      </collision>
      <visual name='${prefix}_wheel_visual'>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
        <material name="yellow"/>
      </visual>
    </link>
  </xacro:macro>

  <xacro:wheel prefix="front_left" xyz="${wheelbase/2} ${wheel_separation/2} 0"/>
  <xacro:wheel prefix="front_right" xyz="${wheelbase/2} -${wheel_separation/2} 0"/>
  <xacro:wheel prefix="rear_left" xyz="-${wheelbase/2} ${wheel_separation/2} 0"/>
  <xacro:wheel prefix="rear_right" xyz="-${wheelbase/2} -${wheel_separation/2} 0"/>

  <!-- Gazebo材质配置 -->
  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="front_left_wheel">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <gazebo reference="front_right_wheel">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <gazebo reference="rear_left_wheel">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <gazebo reference="rear_right_wheel">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find two_wheeled_cart)/config/controller.yaml</parameters>
      <controller_manager_node_name>controller_manager</controller_manager_node_name>
    </plugin>
  </gazebo>

  <ros2_control name="red_bot_hardware" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
      <param name="robot_param">robot_description</param>
    </hardware>
    <joint name="front_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
</robot>